language: java
jdk:
  - openjdk7
  - oraclejdk7
install:
  - gem install bundler
  - bundle install
  - npm install coffee-script
  - export PATH=$PATH:./node_modules/.bin
script: buildr clean package
