repositories:
  remote:
   - http://repo1.maven.org/maven2
   - http://download.eclipse.org/rt/eclipselink/maven.repo
   - http://repository.codehaus.org
   - http://github.com/realityforge/repository/raw/master

artifacts:
  javax_persistence: org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.0.Final
  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javax_transaction: javax.transaction:jta:jar:1.1
  ejb_api: org.apache.geronimo.specs:geronimo-ejb_3.1_spec:jar:1.0.2
  javaee_api: javax:javaee-api:jar:6.0
  javax_annotation: com.google.code.findbugs:jsr305:jar:1.3.9
  jackson_core: org.codehaus.jackson:jackson-core-asl:jar:1.9.4
  jackson_mapper: org.codehaus.jackson:jackson-mapper-asl:jar:1.9.4
  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javax_inject: javax.inject:javax.inject:jar:1

  infomas_annotation_detector: eu.infomas:annotation-detector:jar:3.0.0

  javax_json: org.glassfish:javax.json:jar:1.0.1

  gwt_openlayers: org.gwtopenmaps.openlayers:gwt-openlayers-client:jar:0.9
  gwt_openlayers_server: org.gwtopenmaps.openlayers:gwt-openlayers-server:jar:0.9
  gwt_user: com.google.gwt:gwt-user:jar:2.6.0-rc1
  gwt_dev: com.google.gwt:gwt-dev:jar:2.6.0-rc1
  gwt_gin: com.google.gwt.inject:gin:jar:2.1.2
  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javax_validation_sources: javax.validation:validation-api:jar:sources:1.0.0.GA

  google_guice: com.google.inject:guice:jar:3.0
  google_guice_assistedinject: com.google.inject.extensions:guice-assistedinject:jar:3.0
  aopalliance: aopalliance:aopalliance:jar:1.0 # Required for guice
  findbugs_annotations: com.google.code.findbugs:annotations:jar:1.3.9

  jeo: org.realityforge.jeo:jeo:jar:0.2
  #geolatte_common: org.geolatte:geolatte-common:jar:0.5
  geolatte_geom: org.geolatte:geolatte-geom:jar:0.12-rf
  jts: com.vividsolutions:jts:jar:1.13
  slf4j_api: org.slf4j:slf4j-api:jar:1.6.6
  slf4j_jdk14: org.slf4j:slf4j-jdk14:jar:1.6.6

  rest_field_filter: org.realityforge.rest.field_filter:rest-field-filter:jar:0.1

  geolatte_geom_eclipselink: org.realityforge.jeo.geolatte.jpa.eclipselink:geolatte-geom-eclipselink:jar:0.3

  mgwt: com.googlecode.mgwt:mgwt:jar:1.1.2
